export const AREAS = [
  {
    id: "seguridad",
    nombre: "Seguridad de la Información",
    emoji: "🔒",
    cargos: ["CISO", "Oficial de Seguridad", "Analista de Seguridad", "Coordinador de Seguridad"],
    retos: ["Gestión de accesos", "Políticas de seguridad", "Auditorías", "Cumplimiento normativo", "Incidentes de seguridad"],
    contexto: "Área encargada de la seguridad de la información, ciberseguridad y políticas de protección de datos de la empresa.",
    intel: "Carlos es el CISO y el promotor del proyecto. Está implementando el SGSI (Sistema de Gestión de Seguridad de la Información) desde cero — el rol es nuevo en la empresa. Su preocupación principal es que los gerentes ya usan ChatGPT/Gemini con información sensible sin políticas claras. Quiere liderar la adopción de IA antes de que los gerentes lo hagan de forma desordenada. También actúa como 'vendedor interno' ante el presidente y los gerentes para justificar la alianza con 30X.",
  },
  {
    id: "tecnologia",
    nombre: "Tecnología",
    emoji: "💻",
    cargos: ["Gerente de TI", "Ingeniero de Desarrollo", "Ingeniero de Redes", "Líder Técnico", "Desarrollador"],
    retos: ["Implementación de ERP Dynamics", "Automatización de procesos", "Desarrollo de software", "Infraestructura", "Soporte técnico"],
    contexto: "Área de tecnología e informática. Actualmente implementando Microsoft Dynamics ERP.",
    intel: "El área está en plena implementación de Microsoft Dynamics ERP, lo que genera una carga técnica alta. El ingeniero de desarrollo está manejando Dynamics y desarrollo nuevo al mismo tiempo. Ya experimentó con ChatGPT para automatizar reportes internos (código HTML) y mostró interés en herramientas más avanzadas como Claude. El perfil técnico tiene potencial alto para adopción de IA en desarrollo, automatización y soporte al ERP.",
  },
  {
    id: "financiero",
    nombre: "Financiero Administrativo",
    emoji: "📊",
    cargos: ["Gerente Financiero", "Jefe de Contabilidad", "Tesorero", "Auditor Interno", "Coordinador de Nómina", "Contralor"],
    retos: ["Reportes financieros", "Análisis de datos", "Gestión de nómina", "Auditorías internas", "Proyecciones financieras"],
    contexto: "Área que maneja finanzas, contabilidad, tesorería, nómina y auditoría interna.",
    intel: "Carlos no tiene claridad sobre qué usos de IA aplican a esta área. La ve como un área estándar con perfiles no técnicos. Mencionó coordinador de nómina, jefe de contabilidad, auditores internos y contralores. Podría haber oportunidad en automatización de reportes, análisis financiero o auditoría, pero no hay un campeón interno identificado aún.",
  },
  {
    id: "ventas",
    nombre: "Ventas",
    emoji: "🛒",
    cargos: ["Gerente de Ventas", "Jefe de Crédito", "Jefe de Ventas Regional", "Analista de Ventas", "Coordinador de Ventas", "Asesor Comercial", "Anfitrión"],
    retos: ["Gestión de clientes", "Análisis de ventas", "Seguimiento de leads", "Reportes de desempeño", "Atención al cliente en tienda"],
    contexto: "Área comercial de ventas al consumidor final en tiendas físicas. Maneja muebles y accesorios.",
    intel: "El gerente de ventas coordina todas las tiendas físicas de Colombia (~18 sedes). Tiene coordinadores de ventas (muebles y accesorios), jefe de crédito, jefe regional y un analista de ventas que usa Power BI para análisis de datos. Los anfitriones (tablet en tienda) no usarán IA directamente. Carlos identificó esta área como prioritaria. El analista de ventas con Power BI es el perfil con más potencial inmediato.",
  },
  {
    id: "visual",
    nombre: "Visual",
    emoji: "🎨",
    cargos: ["Coordinador Visual", "Diseñador Visual", "Coordinador de Merchandising", "Asesor de Diseño"],
    retos: ["Tendencias de diseño", "Decoración de espacios", "Fotografía de producto", "Generación de imágenes", "Identidad visual en tienda"],
    contexto: "Área de visual merchandising. Diseña la experiencia visual en tiendas y define tendencias estéticas.",
    intel: "Carlos mencionó esta área como una de las que definitivamente va a usar IA. Hacen viajes de inspiración para buscar tendencias y definen la estética en tienda. El coordinador de visual y el diseñador de visual son los perfiles. Carlos cree que ya buscan tendencias en redes y que la IA de imagen y generación de contenido visual les abre mucho potencial.",
  },
  {
    id: "mercadeo",
    nombre: "Mercadeo e Innovación",
    emoji: "📣",
    cargos: ["Gerente de Mercadeo", "Coordinador de Diseño", "Coordinador de Comunicaciones", "Community Manager", "Supervisor de E-commerce", "Diseñador Gráfico"],
    retos: ["Creación de contenido", "Gestión de redes sociales", "Estrategia digital", "E-commerce", "Análisis de métricas", "Campañas publicitarias"],
    contexto: "Área de mercadeo e innovación. Ya usan ChatGPT Plus. Manejan diseño, comunicaciones, e-commerce y analítica web.",
    intel: "Esta es el área más avanzada en IA según Carlos. Ya tienen ChatGPT Plus/empresarial y lo usan activamente. El gerente de mercadeo es el más alineado con IA de todos los gerentes. Carlos quiere 'atacar' esta área primero. El equipo incluye: coordinador de diseño, coordinador de comunicaciones, community manager, supervisor de e-commerce y diseñador gráfico. Carlos cree que se quedaron solo con ChatGPT y no conocen las otras herramientas. La oportunidad está en ampliar su stack más allá de ChatGPT y estructurar mejor cómo usan la IA.",
  },
  {
    id: "gestion-humana",
    nombre: "Gestión Humana",
    emoji: "👥",
    cargos: ["Gerente de Gestión Humana", "Coordinador de Gestión Humana", "Analista de RRHH", "Coordinador SST"],
    retos: ["Selección de personal", "Capacitaciones", "Seguridad y salud en el trabajo", "Clima organizacional", "Documentación de procesos"],
    contexto: "Área de recursos humanos. También maneja seguridad y salud en el trabajo (SST).",
    intel: "Área integral que maneja tanto RRHH como SST (Seguridad y Salud en el Trabajo). El coordinador de gestión humana tiene muchos procesos de documentación, mapeo de personal y gestión administrativa. Hay oportunidad clara en automatización de selección, onboarding, documentación de políticas y reportes de SST.",
  },
  {
    id: "operaciones",
    nombre: "Operaciones",
    emoji: "⚙️",
    cargos: ["Gerente de Operaciones", "Jefe Nacional de Operaciones", "Jefe de Centro de Distribución", "Planner", "Supervisor de Operaciones", "Coordinador de Instalaciones"],
    retos: ["Logística y distribución", "Planeación de abastecimiento", "Gestión de inventarios", "Coordinación de instalaciones", "Seguimiento de entregas"],
    contexto: "Área de operaciones. Más de 20 personas. Maneja logística, distribución, instalaciones y centro de distribución nacional.",
    intel: "El gerente de operaciones es el único gerente que Carlos describió como 'ya lo entiende'. Ambos llegaron de manera independiente a hablar de IA en la misma semana. Tiene ChatGPT Plus y ya lo usa — incluso hizo un código HTML de reportes. Mencionó interés en usar Claude y Cloud. Carlos le pidió que mapeara quién en su equipo usaría IA. El área tiene más de 20 personas: jefe nacional de operaciones, jefe de CD, planner de abastecimiento, supervisores por ciudad y coordinador de instalaciones. Potencial alto en planeación, logística y seguimiento de entregas.",
  },
  {
    id: "comercial",
    nombre: "Comercial",
    emoji: "🤝",
    cargos: ["Gerente Comercial", "Comprador", "Analista de Compras", "Coordinador de Proveedores"],
    retos: ["Gestión de proveedores", "Análisis de tendencias", "Negociación de compras", "Previsión de demanda", "Selección de productos"],
    contexto: "Área de compras y gestión comercial. Maneja relaciones con proveedores y planeación de compra de muebles y accesorios.",
    intel: "La gerente es mujer y trabaja muy de la mano con mercadeo: mercadeo identifica tendencias y ella las materializa en compras. Maneja proveedores nacionales e internacionales (China), previsión de demanda y selección de productos. Carlos no tiene claridad sobre el nivel de conocimiento de IA en esta área. Oportunidad clara en análisis de tendencias de mercado, previsión de demanda y negociación con proveedores.",
  },
  {
    id: "proyectos",
    nombre: "Proyectos",
    emoji: "🏗️",
    cargos: ["Gerente de Proyectos", "Coordinador B2B", "Asesor de Proyectos Empresariales"],
    retos: ["Ventas B2B", "Gestión de proyectos empresariales", "Cotizaciones grandes", "Seguimiento de clientes corporativos", "Propuestas comerciales"],
    contexto: "Área de ventas empresariales B2B. Maneja proyectos de amoblamiento para empresas.",
    intel: "Gerencia que Carlos acaba de formalizar en el organigrama. Se enfoca en vender amoblamiento completo a empresas (B2B). El equipo está en etapa temprana de exploración de IA. Hay oportunidad grande en prospección B2B, automatización de propuestas comerciales y seguimiento de proyectos.",
  },
  {
    id: "sac",
    nombre: "Servicio al Cliente",
    emoji: "🎧",
    cargos: ["Jefe de SAC", "Coordinador de Servicio al Cliente", "Asesor de Garantías", "Agente de Atención"],
    retos: ["Gestión de garantías", "Atención de PQRS", "Seguimiento de casos", "Tiempos de respuesta", "Satisfacción del cliente"],
    contexto: "Área de servicio al cliente. Maneja garantías, quejas, reclamos y coordinación post-venta.",
    intel: "Carlos la describió como el área que escucha y gestiona todo lo post-venta: garantías, productos que no llegan completos o en mal estado, coordinación de entregas. Es un área reactiva hoy. Potencial alto en automatización de respuestas, clasificación de PQRS, seguimiento de casos y reducción de tiempos de resolución.",
  },
] as const;

export type AreaId = typeof AREAS[number]["id"];

export const HERRAMIENTAS_IA = [
  // Asistentes
  { id: "chatgpt",      nombre: "ChatGPT",         emoji: "🟢", color: "#10A37F", categoria: "Asistentes" },
  { id: "claude",       nombre: "Claude",           emoji: "🟡", color: "#D4A855", categoria: "Asistentes" },
  { id: "gemini",       nombre: "Gemini",           emoji: "🔵", color: "#4285F4", categoria: "Asistentes" },
  { id: "copilot",      nombre: "Copilot",          emoji: "🔷", color: "#0078D4", categoria: "Asistentes" },
  { id: "grok",         nombre: "Grok",             emoji: "⚫", color: "#1D1D1D", categoria: "Asistentes" },
  { id: "perplexity",   nombre: "Perplexity",       emoji: "🔍", color: "#20B2AA", categoria: "Asistentes" },
  { id: "deepseek",     nombre: "DeepSeek",         emoji: "🐋", color: "#1E6FFF", categoria: "Asistentes" },
  { id: "meta-ai",      nombre: "Meta AI",          emoji: "🔮", color: "#0082FB", categoria: "Asistentes" },
  { id: "notebooklm",   nombre: "NotebookLM",       emoji: "📓", color: "#34A853", categoria: "Asistentes" },
  // Imagen
  { id: "midjourney",   nombre: "Midjourney",       emoji: "🎨", color: "#000000", categoria: "Imagen" },
  { id: "dalle",        nombre: "DALL·E",           emoji: "🖼️", color: "#10A37F", categoria: "Imagen" },
  { id: "canva-ia",     nombre: "Canva IA",         emoji: "🎭", color: "#00C4CC", categoria: "Imagen" },
  { id: "firefly",      nombre: "Adobe Firefly",    emoji: "🔥", color: "#FF0000", categoria: "Imagen" },
  { id: "ideogram",     nombre: "Ideogram",         emoji: "✏️", color: "#7C3AED", categoria: "Imagen" },
  { id: "nano-banana",  nombre: "Nano Banana",      emoji: "🍌", color: "#FFD700", categoria: "Imagen" },
  { id: "higgsfield",   nombre: "Higgsfield",       emoji: "🌌", color: "#5B21B6", categoria: "Imagen" },
  { id: "flux",         nombre: "Flux",             emoji: "⚡", color: "#2563EB", categoria: "Imagen" },
  // Video / Audio
  { id: "runway",       nombre: "Runway",           emoji: "🎬", color: "#0F0F0F", categoria: "Video/Audio" },
  { id: "elevenlabs",   nombre: "ElevenLabs",       emoji: "🎙️", color: "#6366F1", categoria: "Video/Audio" },
  { id: "heygen",       nombre: "HeyGen",           emoji: "🎥", color: "#A855F7", categoria: "Video/Audio" },
  { id: "sora",         nombre: "Sora",             emoji: "🌀", color: "#10A37F", categoria: "Video/Audio" },
  { id: "kling",        nombre: "Kling AI",         emoji: "🎞️", color: "#DC2626", categoria: "Video/Audio" },
  { id: "luma",         nombre: "Luma AI",          emoji: "💡", color: "#0EA5E9", categoria: "Video/Audio" },
  // Código
  { id: "github-copilot", nombre: "GitHub Copilot", emoji: "👾", color: "#24292E", categoria: "Código" },
  { id: "cursor",       nombre: "Cursor",           emoji: "⌨️", color: "#1C1C1C", categoria: "Código" },
  { id: "claude-code",  nombre: "Claude Code",      emoji: "🤖", color: "#D4A855", categoria: "Código" },
  { id: "antigravity",  nombre: "Antigravity",      emoji: "🚀", color: "#4F46E5", categoria: "Código" },
  { id: "bolt",         nombre: "Bolt.new",         emoji: "⚡", color: "#F59E0B", categoria: "Código" },
  { id: "v0",           nombre: "v0 (Vercel)",      emoji: "▲",  color: "#000000", categoria: "Código" },
  // Social Media
  { id: "manychat",     nombre: "ManyChat",         emoji: "💬", color: "#007AFF", categoria: "Social Media" },
  { id: "kapso",        nombre: "Kapso",            emoji: "📱", color: "#FF6B35", categoria: "Social Media" },
  { id: "buffer-ai",    nombre: "Buffer AI",        emoji: "📅", color: "#168EEA", categoria: "Social Media" },
  { id: "metricool",    nombre: "Metricool AI",     emoji: "📊", color: "#FF5733", categoria: "Social Media" },
  // Productividad / Automatización
  { id: "n8n",          nombre: "n8n",              emoji: "🔀", color: "#EA4B71", categoria: "Productividad" },
  { id: "manus",        nombre: "Manus",            emoji: "🦾", color: "#6D28D9", categoria: "Productividad" },
  { id: "zapier-ai",    nombre: "Zapier AI",        emoji: "⚡", color: "#FF4A00", categoria: "Productividad" },
  { id: "make",         nombre: "Make",             emoji: "🔗", color: "#6D00CC", categoria: "Productividad" },
  { id: "notion-ai",    nombre: "Notion AI",        emoji: "📝", color: "#000000", categoria: "Productividad" },
  { id: "relevance-ai", nombre: "Relevance AI",     emoji: "🧠", color: "#0F172A", categoria: "Productividad" },
  // Ventas & CRM
  { id: "apollo",       nombre: "Apollo",           emoji: "🎯", color: "#E8501A", categoria: "Ventas" },
  { id: "lusha",        nombre: "Lusha",            emoji: "📇", color: "#FF6B35", categoria: "Ventas" },
  { id: "clay",         nombre: "Clay",             emoji: "🏺", color: "#5B21B6", categoria: "Ventas" },
  { id: "dapta",        nombre: "Dapta",            emoji: "🤝", color: "#0099FF", categoria: "Ventas" },
  { id: "hubspot-ai",   nombre: "HubSpot AI",       emoji: "🧡", color: "#FF7A59", categoria: "Ventas" },
  { id: "salesforce",   nombre: "Salesforce Einstein", emoji: "☁️", color: "#00A1E0", categoria: "Ventas" },
  { id: "instantly",    nombre: "Instantly",        emoji: "✉️", color: "#4F46E5", categoria: "Ventas" },
  { id: "lemlist",      nombre: "Lemlist",          emoji: "🍋", color: "#F59E0B", categoria: "Ventas" },
  // Sin uso / Otra
  { id: "ninguna",      nombre: "Ninguna aún",      emoji: "🚫", color: "#374151", categoria: "Otro" },
  { id: "otra",         nombre: "Otra",             emoji: "➕", color: "#374151", categoria: "Otro" },
] as const;
